= Paleo information diet
September 5th, 2020
:description: How I decided to improve my information diet
:keywords: information media diet paleo

In the last couple of weeks I've been in what I call "low-energy state" which
means I've been feeling shitty and not getting anything done. Furthermore, I've
been thinking about mindfulness (for lack of a better word) for quite some time
now -- I can't remember, when was the last time I deeply thought about what am I
doing with myself. All this lead to the following experiment.

== Motivation
This experiment was motivated by a combination of short-term and longer-term
reasons.

=== Craving distractions
I read that the internet and smart-phones give us dopamine hits that we learn to
crave. I don't know if the science is good, but at least it's a helpful
metaphor.

I was constantly looking for my next hit. It felt like every waking minute, I
just had to cram something into my brain -- a Youtube video, Slack message,
e-mail, new article on Hackernews -- anything. Even though I almost don't use
social media, there was always something to look at.

My brain felt inflamed, my mind foggy. I couldn't focus.

=== Heavy procrastination
I got stuck at work. I'm dealing with an unpleasant task that I don't know how
to finish. This leads to heavy procrastination. Because I feel bad about not
working, I won't allow myself to do anything useful at all (e.g. like life and
home improvement). This results in binging.

At first it was Youtube. When I decided it was time to finally quit I moved on
to TV shows. When I wanted to stop that, I moved to reading a book (this might
sound good but it was not healthy at all).

I realized that I'm just not capable of doing nothing anymore.

=== Information quality
For a long time now I felt that everything I consume is watered down -- blog
posts, Youtube videos, even movies and TV shows. It's all "high calorie, low
information density".

I want to go back to primary sources. Sources that someone put real work into
and got paid for (ad money doesn't count).

I want to choose what I consume more carefully. I want to watch movies and read
books, but my choices need to be deliberate. I want to start learning new things
again (something that feels I haven't been doing for a long time).

I want to ban algorithms from my life -- I will find what I need myself, thank
you very much.


== Goals

Short term:
- Get out of a short term "minimum energy state"
- Stop procrastination, put what's causing it behind me
Long term:
- Strive for a clearer, more focused mind
- Spend more time "with myself"
- Lower my dopamine levels
- Consume media more deliberately, choose more carefully


== Rules
Simply put, I will only consume media that cave people did (none).

- No passive intake
	** Youtube
	** Movies, TV shows
	** Podcasts
- No reading
	** News
	** Blogs
	** Books (both fiction and non-fiction)
- Reading required for work and/or education (e.g. tutorials, documentation) is
allowed
- Limit dopamine hits
	** Social media
	** Checking e-mail, Slack (e.g. only checking it twice a day)
- Music is allowed
- Creating (programming, writing, drawing) is allowed

This strict diet is short term only. I will see where it leads me over time.
Later I will allow myself to consume media again, but hopefully in a more
healthy way.


== Findings so far
It is hard to be in complete silence. I'm listening to a lot of music. I need to
pay attention to that and try to reduce the amount of music as well. However I
find that I'm more deliberate when choosing what to listen to. Before I just
listened to the same things over and over, or just let Spotify suggest me
something. Now I'm trying to find new artists or come back to my old favourites.

Ideas about tasks other that work (e.g. home and life improvement,
side-projects) are slowly coming back. It has only been a couple of days, I need
more data to evaluate this.

I snapped out of my low-energy state for now, completed some task that I've been
putting off.
