Python - what is new in which version?
======================================
June 10, 2019
:source-highlighter: pygments
:description: A summary of new features and improvements in Python versions from 3.5 to 3.8
:keywords: python, python3
:toc:

In this post I would like to summarize which features can be used in which
Python3 versions. I only choose features and changes that are relevant or
interesting to me. There is a link to "What's new" page for each version where
you can find the full list.

== Python 3.5
Released in September 2015. Comes pre-installed on Debian 9 (Stretch) and Ubuntu
16.04. Complete list of changes is https://docs.python.org/3.5/whatsnew/3.5.html[here].

=== New syntax
Coroutines can now be defined with `async` keyword and awaited with `await`
keyword. These keywords are not reserved yet. They will be
become proper reserved keywords in Python 3.7.

`async` can also be used in https://docs.python.org/3.5/reference/compound_stmts.html#async-for[async for]
and https://docs.python.org/3.5/reference/compound_stmts.html#async-with[async with]
statements for asynchronous `for` loops and context managers.

=== New library modules
https://docs.python.org/3.5/library/typing.html#module-typing[typing] module adds support for Type Hints (https://www.python.org/dev/peps/pep-0484/[PEP484]).
While syntax for function annotation was introduced back in Python3.0 (https://www.python.org/dev/peps/pep-3107/[PEP3107],
this module provides some standard tools (such as types Any, Union, Tuple,
Callable, etc.) that can be used in type annotations.

https://docs.python.org/3.5/library/zipapp.html#module-zipapp[zipapp] provides
tools to manage the creation of zip files containing Python code, which can be
executed directly by the Python interpreter.

=== Improvements in stdlib
https://docs.python.org/3.5/library/collections.html#collections.OrderedDict[collections.OrderedDict]
is significantly faster now.

https://docs.python.org/3.5/library/os.html#os.scandir[os.scandir()] is a new
function for
https://docs.python.org/3.5/whatsnew/3.5.html#whatsnew-pep-471[better and
faster way of directory traversal].


== Python 3.6
Released in December 2016. Comes pre-installed on Ubuntu 18.04. Complete list
of changes is https://docs.python.org/3.8/whatsnew/3.6.html[here].

=== New syntax
Formatted string literals
(https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings[f-strings]).
Defined in https://www.python.org/dev/peps/pep-0498/[PEP498].

[source,python]
----
>>> name = "Max"
>>> print(f"Hello, {name}!")
Hello, Max!
----

Support for variable type hints
(https://www.python.org/dev/peps/pep-0498/[PEP526]).


Underscores in numeric literals: `1_000_000`
(https://www.python.org/dev/peps/pep-0515/[PEP515]).


Asynchronous generators (https://www.python.org/dev/peps/pep-0525/[PEP525])
and comprehensions (https://www.python.org/dev/peps/pep-0530/[PEP530]).

=== New library modules
https://docs.python.org/3.8/library/secrets.html#module-secrets[secrets] for
generating cryptographically strong random numbers suitable for managing data
such as passwords, account authentication, security tokens, and related secrets.
Described in https://www.python.org/dev/peps/pep-0505/[PEP506].

=== Implementation improvements
The new implementation of dictionaries is 20% to 25% more compact and preserves
insertion order (but this **should not** be relied upon yet). See this great
https://www.youtube.com/watch?v=p33CVV29OG8[talk by Raymond Hettinger] in which
he explains how dictionaries changed over time.

=== Improvements in stdlib
https://docs.python.org/3.8/library/asyncio.html#module-asyncio[asyncio] is no
longer provisional and the API is considered stable.

A new https://docs.python.org/3.8/whatsnew/3.6.html#whatsnew36-pep519[file
system path protocol] was added
to support https://docs.python.org/3.8/glossary.html#term-path-like-object[path-like object].

The https://docs.python.org/3.8/library/datetime.html#module-datetime[datetime]
module has gained support for https://docs.python.org/3.8/whatsnew/3.6.html#whatsnew36-pep495[Local Time Disambiguation].

`json.load()` and `json.loads()` now support binary input.

A new function https://docs.python.org/3.8/library/random.html#random.choices[random.choices()]
returns a list of specified size with elements from a population with
optional weights.

Class `unittest.mock.Mock` has new methods `assert_called` and
`assert_called_once`.

== Python 3.7
Released in June 2018. Comes pre-installed on Debian 10 (Buster) and  Ubuntu
18.04 and 19.04. Complete list of changes is https://docs.python.org/3.8/whatsnew/3.7.html[here].

=== New syntax features
Postponed evaluation of type annotations (https://www.python.org/dev/peps/pep-0526/[PEP526]).

* Annotations can now support forward references
* Annotations are cheaper and faster to store

`async` and `await` are now reserved keywords.

=== New library modules
https://docs.python.org/3.8/library/dataclasses.html#module-dataclasses[dataclasses]
provides a decorator and functions for automatically adding generated special
methods such as `__init__()` and `__repr__()` to user-defined classes. It is useful
when you need to create a simple class that only holds data but has no
behavior.

=== New built-in features
https://docs.python.org/3.8/library/functions.html#breakpoint[breakpoint()] function for debuggers.

Dictionaries now officially preserve insertion order of elements.

=== Improvements in stdlib
https://docs.python.org/3.8/library/asyncio.html#module-asyncio[asyncio]
received a lot of new features and improvements (high-level `asyncio.run()`
function for running coroutines, many others).

https://docs.python.org/3.8/library/time.html#module-time[time] module now has
support for
https://docs.python.org/3.8/whatsnew/3.7.html#whatsnew37-pep564[nanosecond
resolution].

=== Deprecations
Debian 8, Ubuntu 16, CentOS 7.5 and other platforms that use OpenSSL 0.9.8 and
1.0.1 are no longer supported. At least OpenSSL 1.0.2 is required. You can build
Python3.7 on those platforms but you have to manually link a new OpenSSL
version.

== Python 3.8
Will be released sometime in 2019. Will come pre-installed on Debian 9, Ubuntu
19.04. Complete list of changes is https://docs.python.org/3.8/whatsnew/3.8.html[here].


=== New syntax
https://www.python.org/dev/peps/pep-0572/[Assignment expressions] (the "walrus operator", `:=`):

[source,python]
----
if (n := len(a)) > 10:
    print(f"List is too long ({n} elements, expected <= 10)")
----

https://www.python.org/dev/peps/pep-0570/[Positional only arguments]: There is
new syntax (`/`) to indicate that some function parameters must be specified
positionally.

[source,python]
----
def pow(x, y, z=None, /):
    r = x**y
    if z is not None:
        r %= z
    return r
----

This is in addition to https://www.python.org/dev/peps/pep-3102/[keyword only arguments].

=== Library improvements
`json.tool` has a new option (`--json-lines`) to parse every input line as
separate JSON object.

New class `unittest.mock.AsyncMock` for asynchronous mocking.
