Article list from February of 2020
=================================
March 16th, 2020
:description: Some of the articles I've read in February of 2020. Better late than never.


I've kept up the pace in February, but I can feel that just reading articles is
not going to be enough for me. They are an ok way to pass the time on a train
but don't bring much benefit. For now, I will continue doing this (keeping
a list of articles), but I would like to start reading more books. But that's
going to take some preparation.

- - -

https://www.robinsloan.com/notes/home-cooked-app/[An app can be a home-cooked meal]
and https://web.archive.org/web/20040411202042/http://www.shirky.com/writings/situated_software.html[Shirky: Situated Software]
are related to the theme of sustainable software. I'm not planning on writing
any applications yet. Thought I'm thinking about something else -- ditching
Facebook for keeping in contact with my group of close friends in favor of
something smaller, private. And possibly self-hosted.

- - -

https://changelog.com/podcast/201[Why SQLite succeeded as a database with Richard Hipp, creator of SQLite (The Changelog #201)]
is a podcast, althought there is a transcript. I always knew SQLite existed but this
interview got me interested. I am now looking for ways to use it in some
project.

- - -

https://eev.ee/blog/2020/02/01/old-css-new-css/?fbclid=IwAR1oxGs11ixev9c6qaK1yy8oiZvc4lB7dyxebGpcrec6bFxM0qzJqz03WqM[Old CSS, new CSS / fuzzy notepad]
sent shivers down my spine. How could the web ever get to where it is
today?

- - -

https://blog.discordapp.com/why-discord-is-switching-from-go-to-rust-a190bbca2b1f[Why Discord is switching from Go to Rust - Discord Blog]

I've wanted to get into more programming languages for a long time. Go seemed
like something I would enjoy, but lately, Rust seems more and more appealing.
We now have some code done in Rust, and I'm tempted to give it a go.

- - -

https://www.bbc.com/worklife/article/20200121-why-procrastination-is-about-managing-emotions-not-time[Why procrastination is about managing emotions, not time - BBC Worklife]
and https://en.m.wikipedia.org/wiki/Acceptance_and_commitment_therapy[Acceptance and commitment therapy - Wikipedia]
got my attention because I'd never thought about procrastination like that. In
all the years of trying to battle procrastionation. I always treated like a time
management problem (like most people, I imagine).

- - -

https://newrepublic.com/article/156202/silicon-valley-economy-here-its-nightmare?utm_source=newsletter&utm_medium=email&utm_campaign=audm[The Silicon Valley Economy Is Here. And It’s a Nightmare]
and https://newrepublic.com/article/156411/end-gop[End the GOP] are only the only two
articles from The New Republic that I found worth reading this month. I'm honestly
disappointed with TNR's mailing list. It's mostly paid political campaign
advertising and podcast promotion (I don't listen to podcasts). I'm going to
un-subscribe.

- - -

https://sneak.berlin/20200220/discord-is-not-an-acceptable-choice-for-free-software-projects/[Jeffrey Paul: Discord Is Not An Acceptable Choice For Free Software Projects]

I've never used Discord, and I don't plan to. Now I also have a reason why.

- - -

https://latacora.micro.blog/2020/02/19/stop-using-encrypted.html[Latacora - Stop Using Encrypted Email]

I wasn't and I won't now.

- - -

February was the month that Avast got a lot of flak for selling users data
through Jumpshot. There was a lot of mostly bad and some ok press. https://sparktoro.com/blog/avasts-shutdown-of-jumpshot-will-harm-the-web-and-the-world/[Avast's Shutdown of Jumpshot Will Harm the Web and the World | SparkToro]
and https://www.euro.cz/blogy/zly-avast-a-velka-lekce-pokrytectvi[Zlý Avast a velká lekce pokrytectví - Euro.cz]

- - -

This sounds too good to be true: https://newatlas.com/energy/hb11-hydrogen-boron-fusion-clean-energy/[Radical hydrogen-boron reactor leapfrogs current nuclear fusion tech].

- - -

https://threadreaderapp.com/thread/927593460642615296.html[Thread by @gravislizard: "almost everything on computers is perceptually slower than it was in 1983 amber-screen library computer in 1998: type in two words and hit F […]"]
is just a rant about crappy software that seems to surround us. I can agree with
that. What I did not enjoy is the format - using long Twitter threads is just
lazy. Then again, maybe it's the best format for angry rants.

- - -

In no particular order:

* https://commoncog.com/blog/to-get-good-go-after-the-metagame/[To Get Good, Go After The Metagame]
* https://medium.com/swlh/seniority-in-software-engineering-aabf9706c4b0[Seniority in Software Engineering - The Startup - Medium]
* https://cutle.fish/blog/12-signs-youre-working-in-a-feature-factory[12 Signs You’re Working in a Feature Factory | @johncutlefish's blog]
* https://dagblog.cz/velvoff-debriefieng-i-technologie-964b974643a1[Velvon debriefing I. — Technologie - dagblog]
* https://medium.com/@cairndubh/functional-obfuscation-cc54198b0acd[Functional obfuscation - Brian Duff - Medium]
* https://www.theatlantic.com/health/archive/2020/02/most-annoying-corporate-buzzwords/606748/[The Most Annoying Corporate Buzzwords - The Atlantic]
* https://blog.usejournal.com/monoids-to-groupoids-492c35105113[Did Functional Programming get it wrong? - Noteworthy - The Journal Blog]
* https://blog.acolyer.org/2020/02/12/lets-encrypt-an-automated-certificate-authority-to-encrypt-the-entire-web/[Let's Encrypt: an automated certificate authority to encrypt the entire web – the morning paper]
* https://srconstantin.posthaven.com/how-to-make-a-memex[How to Make A Memex - Sarah Constantin]
* https://blog.acolyer.org/2020/02/14/programs-life-cycles-laws/[Programs, life cycles, and laws of software evolution – the morning paper]
* https://www.inc.com/geoffrey-james/its-official-open-plan-offices-are-now-dumbest-management-fad-of-all-time.html[It's Official: Open-Plan Offices Are Now the Dumbest Management Fad of All Time | Inc.com]
* https://www.transposit.com/blog/2020.01.30-writing-runbook-documentation-when-youre-an-sre/[Writing Runbook Documentation When You’re An SRE · Transposit]
* https://www.collaborativefund.com/blog/gains/[Wealth Is What You Don't Spend · Collaborative Fund]
* https://softwaremaniacs.org/blog/2020/02/05/dicts-ordered/en/[Dicts are now ordered, get used to it]
* http://m.nautil.us/issue/81/maps/theres-no-homunculus-in-our-brain-who-guides-us[There’s No Homunculus In Our Brain Who Guides Us - Issue 81: Maps - Nautilus]
* https://www.infoq.com/articles/metrics-original-sin/[The Original Sin of Software Metrics]
* https://blog.nelhage.com/post/reflections-on-performance/[Reflections on software performance - Made of Bugs]
* https://scottlocklin.wordpress.com/2020/02/21/andreessen-horowitz-craps-on-ai-startups-from-a-great-height/[Andreessen-Horowitz craps on “AI” startups from a great height | Locklin on science]
* https://tech.channable.com/posts/2020-02-05-opnieuw.html[Channable - Opnieuw: A simple and intuitive retrying library for Python]

